# FarmingPlugin Configuration
# MMO RPG Farming System

# Database settings
database:
  host: localhost
  port: 3306
  # "name" and "user" keys are also accepted for compatibility
  name: plantation
  user: root
  password: ""

# Plantation world and layout settings
plantations:
  world: world
  base:
    origin:
      x: 0
      y: 100
      z: 0
    plot:
      width: 16
      height: 16
      depth: 16
      fence_material: OAK_FENCE
      gate_material: OAK_FENCE_GATE
    spacing: 5
    grid:
      rows: 10
      cols: 10
  
  # Protection settings
  protection:
    block_build: true
    block_pvp: false
  
  # Hologram settings
  holograms:
    enabled: true
    title: "&e{farm_display}"
    ready: "&a&lREADY! &7Right-click to collect"
    running: "&7Next: &a{time_left}"
  
  # Drop settings
  drop:
    radius: 0.6

# Starter kit for new players
starter_kit:
  enabled: true

# Auto-save settings
auto_save:
  enabled: true
  interval_minutes: 5

# Metrics
metrics:
  enabled: true

# Debug mode
debug: false
