# Farming Plugin Configuration

# Database settings
database:
  host: localhost
  port: 3306
  name: plantation
  user: root
  password: ""

# Economy settings
# Economy settings
economy:
  enabled: true
npc:
  enabled: true
  temporary_permission_command: "npcmd add plantation.use plantation"
# Teleportation settings
teleport:
  require_level: true
  minimum_level: 85
  cooldown_seconds: 5
  require_permission: true
  permission: "plantation.use"

plantations:
  world: world
  base:
    origin:
      x: 1000
      y: 100
      z: 1000
    plot:
      width: 17
      height: 15
      depth: 16
      fence_material: OAK_FENCE
      gate_material: OAK_FENCE_GATE
    spacing: 20
    grid:
      rows: 10
      cols: 10
  # Protection settings
  protection:
    block_build: true
    block_pvp: false
    block_farm_blocks: true
  # Hologram settings
  holograms:
    enabled: true
    update_interval: 30 # seconds  # Drop settings
  drop:
    radius: 0.6

fruits:
  sweet_berries:
    display_name: "&dSweet Berries"
    sell_price: 50000
  golden_melon:
    display_name: "&6Golden Melon Slice"
    sell_price: 75000
  mystic_mushroom:
    display_name: "&5Mystic Mushroom"
    sell_price: 100000
  enchanted_pumpkin:
    display_name: "&6Enchanted Pumpkin Slice"
    sell_price: 125000
  ethereal_flower:
    display_name: "&dEthereal Blossom"
    sell_price: 200000
  ancient_seed:
    display_name: "&2Ancient Mangrove Seed"
    sell_price: 350000
  desert_date:
    display_name: "&eDesert Golden Date"
    sell_price: 500000

# Starter kit for new players
starter_kit:
  enabled: false

# Auto-save settings
auto_save:
  enabled: true
  interval_minutes: 5

# Metrics
metrics:
  enabled: true

# Debug mode
debug: false

# --- PLANTATION LAYOUT & WORLD ---
plantation:
  world: world
  spawn:
    x: 1008
    y: 64
    z: 998
  holograms:
    y_offset: -0.6
  rebuild_on_join: true

# --- TRYB TESTOWY ---
test_mode:
  enabled: true
  growth_minutes: 1

# (opcjonalnie) materiały pod uprawy/ścieżki
blocks:
  path: DIRT_PATH
  ground: GRASS_BLOCK

