name: FarmingPlugin
main: org.maks.farmingPlugin.FarmingPlugin
version: 1.0
api-version: 1.20
author: maks
description: Advanced farming system with plantations

depend:
  - Vault

commands:
  plantation:
    description: Main plantation command
    usage: /plantation [tp|info|stats|settings|help]
    aliases: [farm, farms, plant]

permissions:
  plantation.use:
    description: Allows using plantation system
    default: false

  plantation.admin:
    description: Admin commands for plantations
    default: op
    children:
      plantation.admin.build: true
      plantation.admin.reload: true
      plantation.admin.reset: true
      plantation.admin.give: true
      plantation.admin.setlevel: true
      plantation.admin.debug: true

  plantation.admin.build:
    description: Build on other players' plantations
    default: op

  plantation.admin.reload:
    description: Reload plugin configuration
    default: op

  plantation.admin.reset:
    description: Reset player plantations
    default: op

  plantation.admin.give:
    description: Give materials to players
    default: op

  plantation.admin.setlevel:
    description: Set farm levels
    default: op

  plantation.admin.debug:
    description: Use debug commands
    default: op

